apiVersion: v2
name: codearena
description: CodeArena - Real-time Competitive Coding Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - coding
  - competitive
  - kubernetes
  - microservices
  - real-time
maintainers:
  - name: Raj
    email: rpdinkar92260@gmail.com
home: https://github.com/Raj-glitch-max/code-arena-access
sources:
  - https://github.com/Raj-glitch-max/code-arena-access
